Infomap --directed --flow-network --two-level -i pajek data/net_202001_05.net mapequation > mapequation/output_infomap_05.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_06.net mapequation > mapequation/output_infomap_06.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_07.net mapequation > mapequation/output_infomap_07.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_08.net mapequation > mapequation/output_infomap_08.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_09.net mapequation > mapequation/output_infomap_09.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_10.net mapequation > mapequation/output_infomap_10.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_11.net mapequation > mapequation/output_infomap_11.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_12.net mapequation > mapequation/output_infomap_12.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_13.net mapequation > mapequation/output_infomap_13.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_14.net mapequation > mapequation/output_infomap_14.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_15.net mapequation > mapequation/output_infomap_15.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_16.net mapequation > mapequation/output_infomap_16.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_17.net mapequation > mapequation/output_infomap_17.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_18.net mapequation > mapequation/output_infomap_18.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_19.net mapequation > mapequation/output_infomap_19.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_20.net mapequation > mapequation/output_infomap_20.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_21.net mapequation > mapequation/output_infomap_21.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_22.net mapequation > mapequation/output_infomap_22.txt &&
Infomap --directed --flow-network --two-level -i pajek data/net_202001_23.net mapequation > mapequation/output_infomap_23.txt
